steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ['compose', '-f', 'docker-compose-network.yaml', '-f', 'docker-compose-deploy.yaml', 'build']
    id: build-image
    
  - name: "gcr.io/cloud-builders/docker"
    args: ['compose', '-f', 'docker-compose-network.yaml', '-f', 'docker-compose-deploy.yaml', 'run', 'staging-deploz', '-c', '"./deploz.sh"', '--network=cloudbuild']
    id: deploy-dataflow
    env:
      - GCP_PROJECT_ID=kissam-testing-project
      - TOPIC=projects/kissam-testing-project/topics/topico
      - PROJECT_NAME=kissam-testing-project
      - TEMP_BUCKET=gs://test-bucket-dg/temp_location
      - DATAFLOW_RUNNER_SERVICE_ACCOUNT=714950193027-compute@developer.gserviceaccount.com
    waitFor:
      - 'build-image'
serviceAccount: 'projects/kissam-testing-project/serviceAccounts/714950193027-compute@developer.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
  